eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'spree_core', path: '../core'
gem 'spree_api', path: '../api'

gemspec

# gem 'bootstrap-sass', :path => "C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.3.5.1"
gem 'bootstrap-sass', github: 'karla-holman/bootstrap-sass-jcauto'